--SCRIPT DDL PARA O MODELO PESQUISADOR

--ÁREA DE PESQUISA
CREATE TABLE AreaPesquisa (
 	 CODIGO INTEGER NOT NULL,
     INDICE_RELEVANCIA INTEGER NOT NULL,
     NOME VARCHAR(50) NOT NULL,
     DESCRICAO VARCHAR(100) NOT NULL
);

--PK
ALTER TABLE AreaPesquisa ADD CONSTRAINT AREA_pk PRIMARY KEY (CODIGO);

--RENAME
ALTER TABLE AREAPESQUISA RENAME TO AREA_PESQUISA;
 
--INSERINDO DADOS DE TESTE
INSERT INTO AREA_PESQUISA (CODIGO, INDICE_RELEVANCIA, NOME, DESCRICAO)
VALUES (101, 3, 'App Móveis', 'Aplicativos Móveis');


--INSTITUIÇÃO
CREATE TABLE INSTITUICAO (
	CNPJ NUMERIC(14) NOT NULL,
	LATITUDE FLOAT NOT NULL,
	LONGITUDE FLOAT NOT NULL,
	NOME VARCHAR(50) NOT NULL,
	TIPO VARCHAR(20) NOT NULL,
	ESTADO VARCHAR(45) NOT NULL,
	CIDADE VARCHAR(50) NOT NULL
);

--PK
ALTER TABLE INSTITUICAO ADD CONSTRAINT INSTITUICAO_PK
PRIMARY KEY (CNPJ);

--ASSESSOR
CREATE TABLE ASSESSOR (
	CPF NUMERIC(11) NOT NULL,
	GRAU INTEGER NOT NULL,
	--DATA_NASCIMENTO DATE NOT NULL,
	NOME VARCHAR(50) NOT NULL,
	SEXO CHAR NOT NULL,
	CNPJ NUMERIC(14) NOT NULL
);

--PK
ALTER TABLE ASSESSOR ADD CONSTRAINT ACESSOR_PK PRIMARY KEY (CPF);

--FK
ALTER TABLE ASSESSOR ADD CONSTRAINT ACESSOR_INST_FK
FOREIGN KEY (CNPJ) REFERENCES INSTITUICAO (CNPJ);

--PESQUISADOR
CREATE TABLE PESQUISADOR (
	CPF NUMERIC(11) NOT NULL,
	NOME VARCHAR(50) NOT NULL,
	SEXO CHAR NOT NULL,
--	NASCIMENTO DATE NOT NULL, --NÃO VAMOS MEXER COM DATA JÁ
	CNPJ NUMERIC(14) NOT NULL
);

--PK
ALTER TABLE PESQUISADOR ADD CONSTRAINT PESQUISADOR_PK PRIMARY KEY (CPF);

--FK
ALTER TABLE PESQUISADOR ADD CONSTRAINT PESQ_INST_FK
FOREIGN KEY (CNPJ) REFERENCES INSTITUICAO (CNPJ);

--PROJETO
CREATE TABLE PROJETO (
	CODIGO INTEGER NOT NULL,
	--SUBMISSAO DATE NOT NULL,
    TITULO VARCHAR(100) NOT NULL,
    DURACAO INTEGER NOT NULL,
	CNPJ NUMERIC(14) NOT NULL,
	CPF NUMERIC(14) NOT NULL,
    CODIGO_AREA INTEGER NOT NULL
);

--PK
ALTER TABLE PROJETO ADD CONSTRAINT PROJETO_PK PRIMARY KEY (CODIGO);

--CHAVE ESTRANGEIRA QUE VEM DA ÁREA DE PESQUISA
ALTER TABLE PROJETO ADD CONSTRAINT AREA_FK 
FOREIGN KEY (CODIGO_AREA) REFERENCES AREA_PESQUISA (CODIGO);

--FK DA INSTITUICAO
ALTER TABLE PROJETO ADD CONSTRAINT PROJ_INST_FK
FOREIGN KEY (CNPJ) REFERENCES INSTITUICAO(CNPJ);

--FK DO PESQUISADOR
ALTER TABLE PROJETO ADD CONSTRAINT PROJ_PESQ_FK
FOREIGN KEY (CPF) REFERENCES PESQUISADOR (CPF);


--AVALIA
CREATE TABLE AVALIA (
	CPF NUMERIC(11) NOT NULL,
	CODIGO INTEGER NOT NULL,
	--DATA_ENVIO DATE NOT NULL,
	--DATA_RESPOSTA DATE NOT NULL,
	RESULTADO VARCHAR(20) NOT NULL
);

--PK
ALTER TABLE AVALIA ADD CONSTRAINT AVALIA_PK PRIMARY KEY (CPF, CODIGO);

--FK
ALTER TABLE AVALIA ADD CONSTRAINT AVALIA_ASSESOR_FK
FOREIGN KEY (CPF) REFERENCES ASSESSOR (CPF);

ALTER TABLE AVALIA ADD CONSTRAINT AVALIA_PROJ_FK
FOREIGN KEY (CODIGO) REFERENCES PROJETO (CODIGO);


--TABELA PODE AVALIAR
CREATE TABLE PODE_AVALIAR (
	CODIGO INTEGER NOT NULL,
	CPF NUMERIC(11) NOT NULL
);

--PK
ALTER TABLE PODE_AVALIAR ADD CONSTRAINT PODE_AVALIAR_PK PRIMARY KEY (CODIGO, CPF);

--FK
ALTER TABLE PODE_AVALIAR ADD CONSTRAINT PODE_AVALIAR_ASSESOR_FK
FOREIGN KEY (CPF) REFERENCES ASSESSOR (CPF);

ALTER TABLE PODE_AVALIAR ADD CONSTRAINT PODE_AVALIAR_AREA_FK
FOREIGN KEY (CODIGO) REFERENCES AREA_PESQUISA (CODIGO);

--FIM DO SCRIPT
